# Base my image on the latest version of Nginx
FROM nginx:latest

# Copy the Nginx configuration file into the configuration directory
# This ensures Nginx is set up to serve the  app on port 9000
COPY ./proxy.conf /etc/nginx/conf.d/default.conf
