# Base my image on the latest version of Nginx
FROM nginx:latest

# Copy the front-end files into the appropriate directory for Nginx
# These files will be served as static files
COPY ./softy-pinko-front-end /var/www/html/softy-pinko-front-end

# Copy the Nginx configuration file into the configuration directory
# This ensures Nginx is set up to serve the  app on port 9000
COPY ./softy-pinko-front-end.conf /etc/nginx/conf.d/default.conf

# Display the instructions in the build output
RUN echo "!!INSTRUCTIONS!!"
RUN echo "To test, run: docker run -d -p 9000:9000 my_frontend_app"

